# Generated by Django 4.0.2 on 2022-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('room', models.TextField(null=True)),
                ('budget', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
