# Generated by Django 4.0.3 on 2022-05-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='room',
        ),
        migrations.AddField(
            model_name='hostel',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
